$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$srcDir    = Join-Path $scriptDir "src"
$distDir   = Join-Path $scriptDir "dist"
$outFile   = Join-Path $distDir "API-Tester.ps1"

if (-not (Test-Path $distDir)) {
    New-Item -ItemType Directory -Path $distDir | Out-Null
}

if (Test-Path $outFile) {
    Remove-Item $outFile -Force
}

# The specific order is crucial to ensure functions are defined before they are called
$filesToMerge = @(
    "Config\Constants.ps1"
    
    "Utils\Helpers.ps1"
    "Utils\Formatting.ps1"
    
    "UI\Controls.ps1"
    
    "Core\StateManager.ps1"
    "Core\Auth.ps1"
    "Core\HttpClient.ps1"
    "Core\TestRunner.ps1"
    "Core\Updater.ps1"
    
    # Dialogs can be loaded in any order as long as they are before MainForm
    "UI\Dialogs\AboutDialog.ps1"
    "UI\Dialogs\AuthPanel.ps1"
    "UI\Dialogs\CookieJar.ps1"
    "UI\Dialogs\EnvironmentEditor.ps1"
    "UI\Dialogs\EnvironmentManagerWindow.ps1"
    "UI\Dialogs\GrpcClient.ps1"
    "UI\Dialogs\JwtTool.ps1"
    "UI\Dialogs\LogViewer.ps1"
    "UI\Dialogs\MonitorChartWindow.ps1"
    "UI\Dialogs\MonitorEditor.ps1"
    "UI\Dialogs\MonitorEmailSettings.ps1"
    "UI\Dialogs\MonitorManager.ps1"
    "UI\Dialogs\MonitoringDashboard.ps1"
    "UI\Dialogs\ProxySettings.ps1"
    "UI\Dialogs\ReportGenerator.ps1"
    "UI\Dialogs\SettingsWindow.ps1"
    "UI\Dialogs\VariablesEditor.ps1"
    "UI\Dialogs\WebSocketClient.ps1"
    
    "UI\MainForm.ps1"
    "Main.ps1" # The very bottom invocation: New-APIForm
)

$outBuffer = New-Object System.Text.StringBuilder

# Add header
$outBuffer.AppendLine("# 🧪 PowerShell API Tester (Compiled version)") | Out-Null
$outBuffer.AppendLine("# This file is auto-generated by Build.ps1. Do not edit directly.") | Out-Null
$outBuffer.AppendLine() | Out-Null

foreach ($relPath in $filesToMerge) {
    $fullPath = Join-Path $srcDir $relPath
    if (Test-Path $fullPath) {
        Write-Host "Merging: $relPath"
        $content = [System.IO.File]::ReadAllText($fullPath, [System.Text.Encoding]::UTF8)
        $outBuffer.AppendLine($content) | Out-Null
    } else {
        Write-Warning "File not found: $fullPath"
    }
}

[System.IO.File]::WriteAllText($outFile, $outBuffer.ToString(), [System.Text.Encoding]::UTF8)

Write-Host "`nBuild complete: $outFile"
Write-Host "Running syntax check on the compiled file..."

$errors = $null
$null = [System.Management.Automation.Language.Parser]::ParseFile($outFile, [ref]$null, [ref]$errors)

if ($errors.Count -eq 0) {
    Write-Host "✅ Syntax OK." -ForegroundColor Green
} else {
    Write-Host "❌ Syntax Errors Found:" -ForegroundColor Red
    foreach ($err in $errors) {
        Write-Host "Line $($err.Extent.StartLineNumber): $($err.Message)" -ForegroundColor Red
    }
}
